server:
   port: 9601
#   servlet:
#      context-path: "/data"
spring:
   application:
      name: galileo-start
   profiles:
      active: dev
   redis:
      host: bronze-redis
      port: 6379
      database: 0
      password: Iml123123

